# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: install packages
        run: |
          sudo apt-get -q update
          sudo apt-get install xmltv-utilsudo apt-get install -y sed.
   
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          wget "https://raw.githubusercontent.com/free-greek-iptv/greek-iptv/master/Greekstreamtv.m3u"
          sed -e "/#EXTM3U/d" -e "s/.*,/Channel name:/" -e "s/^http/URL1:http/" -e "s/https/http/g"  "Greekstreamtv.m3u" > "WebTV List.txt"

      - name: commit 
        run: |
          git config --local user.name ${{ github.actor }}
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git add WebTV List.txt
          git commit -m "new data from job ${{ github.run_number }}"
          git pull origin "${{ github.ref }}" --autostash --rebase -Xours
          git push origin "${{ github.ref }}"
          git log --name-only
          git status
      
